Added global alert_overrides option
echoes-tech/puppet-monit pull request #21
Opened 2016-01-04 09:49 UTC by grega

Allows:

```
  class { 'monit':
    alert_emails    => 'example@email.com',
    alert_overrides => 'but not on { pid, resource, instance }',
  }
```

which results in the following in `monitrc`:

```
 set alert example@email.com but not on { pid, resource, instance }
```

Ref: https://mmonit.com/monit/documentation/monit.html#Setting-an-event-filter

2016-01-04 09:55 UTC, grega commented
Travis build failure doesn't appear to be related to changes in this PR:

```
Failures:

  1) monit On a RedHat OS with no package name specified should contain Package[monit]

     Failure/Error: should contain_package('monit')

     Puppet::PreformattedError:
       Evaluation Error: Error while evaluating a Function Call, 'versioncmp' parameter 'a' expects a String value, got Undef at /home/travis/build/echoes-tech/puppet-monit/spec/fixtures/modules/monit/manifests/params.pp:47:10 on node testing-worker-linux-docker-f341370a-3190-linux-4.prod.travis-ci.org
```

2016-02-04 21:00 UTC, dgarbus commented
I would also like to see this merged. I am currently running this in my test environment without issue.

2017-03-15 10:05 UTC, FlorentPoinsaut requested changes
Hello,

Thank you for this PR.
I propose some changes.
Could you please update it?
Adding tests would be great :-)

Thank you.
Regards,

2017-03-15 10:05 UTC, floSoX commented on README.md
> +##### `alert_overrides`
Can you name the variable alert_context please?

2017-03-15 10:46 UTC, grega commented on README.md
> +##### `alert_overrides`
Done 👍

2021-02-23 18:01 UTC, closed without merging